version: '3.1'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/prometheus
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - promnet
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/alertmanager
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
    ports:
      - 9093:9093
    networks:
      - promnet
    restart: unless-stopped

  karma:
    image: lmierzwa/karma
    volumes:
      - ./karma/karma.yaml:/karma.yaml
    command:
      - '--config.file /karma.yaml'
    ports:
      - 8888:8080
    networks:
      - promnet
    restart: unless-stopped

  alerta:
    image: alerta/alerta-web
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
#      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=mongodb://db:27017/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io #default password: alerta
      - PLUGINS=remote_ip,reject,heartbeat,blackout,prometheus
      - ALERTMANAGER_API_URL=http://alertmanager:9093
    networks:
      - promnet
      - dbnet
    restart: unless-stopped

  db:
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - dbnet
    restart: unless-stopped

networks:
  promnet:
    driver: bridge
  dbnet:
    driver: bridge
