{
 "title": "Linux node_exporter USE Method",
 "tags": [
  "linux",
  "prometheus",
  "node_exporter",
  "use-method"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",host=~\"$host\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',host=~\"$host\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",host=~\"$host\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='idle',host=~\"$host\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',host=~\"$host\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',host=~\"$host\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IO Wait"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{host=~\"$host\",job=~\"$job\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{host=~\"$host\",job=~\"$job\"}",
     "legendFormat": "Processes in runnable state"
    },
    {
     "expr": "node_load1{host=~\"$host\",job=~\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "count without (cpu, mode) (node_cpu_seconds_total{mode=\"idle\",host=~\"$host\",job=~\"$job\"})",
     "legendFormat": "Number of Cores"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{host=~\"$host\",job=~\"$job\"} - node_memory_SwapFree_bytes{host=~\"$host\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\",job=~\"$job\"} - node_memory_MemFree_bytes{host=~\"$host\",job=~\"$job\"} - (node_memory_Cached_bytes{host=~\"$host\",job=~\"$job\"} + node_memory_Buffers_bytes{host=~\"$host\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{host=~\"$host\",job=~\"$job\"} + node_memory_Buffers_bytes{host=~\"$host\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{host=~\"$host\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$host\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_vmstat_pgmajfault{host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "Pgmajfault - Major page fault operations"
    },
    {
     "expr": "irate(node_vmstat_pgpgin{host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "Pagesin - Page in operations"
    },
    {
     "expr": "irate(node_vmstat_pgpgout{host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "Pagesout - Page out operations"
    },
    {
     "expr": "irate(node_vmstat_pswpin{host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "Pswpin - Pages swapped in"
    },
    {
     "expr": "irate(node_vmstat_pswpout{host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "Pswpout - Pages swapped out"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\",host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\",host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Network Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{device!=\"lo\",host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{device!=\"lo\",host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    },
    {
     "expr": "irate(node_network_receive_fifo_total{device!=\"lo\",host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive fifo"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{device!=\"lo\",host=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit fifo"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{host=~\"$host\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{host=~\"$host\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{host=~\"$host\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - IO time"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Filesystem usage",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{job=~\"$job\",host=~\"$host\",fstype=~\"ext.|xfs\"} / node_filesystem_size_bytes{job=~\"$job\",host=~\"$host\",fstype=~\"ext.|xfs\"}) * 100",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Percentage of inodes usage",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_files_free{job=~\"$job\",host=~\"$host\",fstype=~\"ext.|xfs\"} / node_filesystem_files{job=~\"$job\",host=~\"$host\",fstype=~\"ext.|xfs\"} * 100)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  }
 ]
}