global:
  scrape_interval: 15s
  evaluation_interval: 15s
  #external_labels:
  #  dc: dc1

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
#      - alertmanager2:9093

# load rules files
rule_files:
  - "rules/*.rules.yml"

# remote read/write to/from M3DB
#remote_read:
#  - url: 'http://m3db-server:7201/api/v1/prom/remote/read'
#    # to test reading even when local Prometheus has the data
#    read_recent: true
#remote_write:
#  - url: 'http://m3db-server:7201/api/v1/prom/remote/write'

scrape_configs:
  # prometheus targets
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # pushgateway
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
  
  # alertmanager targets
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # karma target
  - job_name: 'karma'
    static_configs:
      - targets: ['karma:8080']

  # node_exporter targets
  - job_name: 'node_exporter'
    file_sd_configs:
      - files:
        - /etc/prometheus/node_exporter-targets.json

  # telegraf targets
  - job_name: 'telegraf'
    file_sd_configs:
      - files:
        - /etc/prometheus/telegraf-targets.json
