apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: PrometheusLTS
  type: prometheus
  access: proxy
  orgId: 1
  url: http://${PROM_SERVER_ADDR}:${PROM_SERVER_PORT}
  password:
  user:
  database:
  basicAuth:
  basicAuthUser: 
  basicAuthPassword: 
  withCredentials:
  isDefault: true
  version: 1
  editable: true
