groups:
# Rules for filesystem
- name: Node Exporter Filesystem rules
  rules:
  - record: instance:node_filesystem_avail:ratio
    expr: node_filesystem_avail_bytes{device=~"/dev/.+"} / node_filesystem_size_bytes{device=~"/dev/.+"}

  # Filesystem alerts

  # Filesystem Full Soon
  - alert: Filesystem-FullSoon
    expr: predict_linear(node_filesystem_avail_bytes{fstype=~"(ext.|xfs)"}[6h], 24 * 3600) < 0
    for: 30m
    labels:
      severity: warning
      team: linux-systems
    annotations:
      summary: Filesystem is predicted to be full on the next 24h.
      description: |
        The mount point {{ $labels.mountpoint }} is predicted to be full in the next 24 hours (host {{ if $labels.host }}{{ $labels.host }}{{ else }}{{ $labels.instance }}{{ end }}).

  # Low Disk space
  - alert: Filesystem-DiskSpace
    expr: (
      node_filesystem_avail_bytes{fstype=~"(ext.|xfs)"} /
      node_filesystem_size_bytes{fstype=~"(ext.|xfs)"}
    ) * 100 <= 20
    for: 15m
    labels:
      severity: warning
      team: linux-systems
    annotations:
      summary: Less than 20% disk space left.
      description: |
        On the last 15m the disk space left for mountpoint {{ $labels.mountpoint }} is less than 10% (host {{ if $labels.host }}{{ $labels.host }}{{ else }}{{ $labels.instance }}{{ end }}).

  # No Disk space
  - alert: Filesystem-LowDiskSpace
    expr: (
      node_filesystem_avail_bytes{fstype=~"(ext.|xfs)"} /
      node_filesystem_size_bytes{fstype=~"(ext.|xfs)"}
    ) * 100 <= 10
    for: 15m
    labels:
      severity: critical
      team: linux-systems
    annotations:
      summary: 10% disk space left.
      description: |
        On the last 15m the disk space left for mountpoint {{ $labels.mountpoint }} is less than 10% (host {{ if $labels.host }}{{ $labels.host }}{{ else }}{{ $labels.instance }}{{ end }}).

  # High Inode usage
  - alert: Filesystem-InodeUsage
    expr: (
      node_filesystem_files_free{fstype=~"(ext.|xfs)"} / 
      node_filesystem_files{fstype=~"(ext.|xfs)"}
    ) * 100 <= 20
    for: 15m
    labels:
      severity: critical
      team: linux-systems
    annotations:
      summary: High number of inode usage.
      description: |
        High number of inodes for mountpoint {{ $labels.mountpoint }} for the last 15m (host {{ if $labels.host }}{{ $labels.host }}{{ else }}{{ $labels.instance }}{{ end }}).
