{
 "title": "Linux telegraf Drill Down",
 "description": "Linux drill down using telegraf and prometheus",
 "tags": [
  "linux",
  "prometheus",
  "telegraf",
  "drill-down"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kernel_boot_time,job)"
   },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(kernel_boot_time{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(kernel_boot_time{instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "disk_device",
    "label": "Disk Device",
    "query": "label_values(disk_used_percent{fstype!=\"rootfs\", instance=\"$node:$port\"}, device)"
   },
   {
    "name": "interface",
    "label": "Net Interface",
    "query": "label_values(net_bytes_sent{instance=\"$node:$port\"}, interface)"
   }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "description": "Telegraf Status",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_uptime{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Logged In Users",
   "type": "singlestat",
   "description": "Number of logged users",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_n_users{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "description": "Number of processes",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "processes_total{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "description": "Number of containers in the running state",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "docker_n_containers{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(100-cpu_usage_idle{instance=\"$node:$port\",cpu=\"cpu-total\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "mem_used_percent{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "swap_used_percent{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "disk_used_percent{instance=\"$node:$port\",path=\"/\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "avg(system_load1{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(system_n_cpus{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "avg(system_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(system_n_cpus{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_n_cpus{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_total{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "swap_total{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_load1{instance=\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{instance=\"$node:$port\", cpu=\"cpu-total\",job=~\"$job\"}",
     "legendFormat": "User"
    },
    {
     "expr": "cpu_usage_system{instance=\"$node:$port\", cpu=\"cpu-total\",job=~\"$job\"}",
     "legendFormat": "System"
    },
    {
     "expr": "cpu_usage_idle{instance=\"$node:$port\", cpu=\"cpu-total\",job=~\"$job\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_total{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "mem_total{instance=~\"$node:$port\",job=~\"$job\"} - mem_free{instance=~\"$node:$port\",job=~\"$job\"} - (mem_cached{instance=~\"$node:$port\",job=~\"$job\"} + mem_buffered{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "mem_cached{instance=~\"$node:$port\",job=~\"$job\"} + mem_buffered{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "mem_free{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(swap_total{instance=~\"$node:$port\",job=~\"$job\"} - swap_free{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Basic Net / Disk Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Basic",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_recv{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "recv {{interface}}"
      },
      {
       "expr": "rate(net_bytes_sent{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
       "legendFormat": "trans {{interface}} "
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "graph",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((disk_free{instance=~\"$node:$port\",job=~\"$job\"} * 100) / disk_total{instance=~\"$node:$port\",job=~\"$job\"})",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU Input Plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(100-cpu_usage_idle{instance=\"$node:$port\", cpu=\"cpu-total\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Total %",
   "type": "graph",
   "description": "Total CPU %",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(cpu_usage_system{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(cpu_usage_user{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(cpu_usage_iowait{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IOWait"
    },
    {
     "expr": "sum by (instance)(rate(cpu_usage_irq{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by (instance)(rate(cpu_usage_idle{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum by (instance)(rate(cpu_usage_guest{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Guest"
    },
    {
     "expr": "sum by (instance)(rate(cpu_usage_nice{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Nice"
    },
    {
     "expr": "sum by (instance)(rate(cpu_usage_softirq{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Soft IRQs"
    },
    {
     "expr": "sum by (instance)(rate(cpu_usage_steal{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Steal"
    },
    {
     "expr": "sum by (instance)(rate(usage_guest_nice{cpu=\"cpu-total\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Guest Nice"
    }
   ]
  },
  {
   "title": "CPU Cores - User",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{instance=\"$node:$port\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Cores - System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_system{instance=\"$node:$port\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Mem Input Plugin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "mem_used_percent{instance=\"$node:$port\",job=~\"$job\"}"
      }
     ]
    },
    {
     "title": "Memory Details",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mem_buffered{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Buffered"
      },
      {
       "expr": "mem_cached{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "mem_free{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "mem_active{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "mem_available{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "mem_dirty{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Dirty"
      },
      {
       "expr": "mem_inactive{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive"
      },
      {
       "expr": "mem_mapped{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Mapped"
      },
      {
       "expr": "mem_page_tables{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Page Tables"
      },
      {
       "expr": "mem_shared{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Shared"
      },
      {
       "expr": "mem_slab{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Slab"
      },
      {
       "expr": "mem_swap_cached{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Swap Cached"
      },
      {
       "expr": "mem_commit_limit{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Commit Limit"
      },
      {
       "expr": "mem_committed_as{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Committed_As"
      },
      {
       "expr": "mem_wired{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Wired"
      },
      {
       "expr": "mem_write_back{instance=\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Write Back"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "mem_inactive{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "mem_inactive{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      }
     ]
    },
    {
     "title": "Memory Commited",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "mem_committed_as{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "mem_commit_limit{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "mem_write_back{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "mem_write_back_tmp{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "mem_dirty{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "Memory Shared and Mapped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "mem_mapped{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
      },
      {
       "expr": "mem_shared{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
      }
     ]
    },
    {
     "title": "Memory Vmalloc",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "mem_vmalloc_chunk{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
      },
      {
       "expr": "mem_vmalloc_total{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "mem_vmalloc_used{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "Memory HugePages Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "mem_huge_pages_total{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "HugePages - Total size of the pool of huge pages"
      },
      {
       "expr": "mem_huge_page_size{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Hugepagesize - Huge Page size"
      },
      {
       "expr": "mem_huge_pages_free{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "HupePageFree"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Device $disk_device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "disk_device",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk used - $disk_device",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "disk_used_percent{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Disk capacity - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "disk_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free on {{path}}"
      },
      {
       "expr": "disk_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used on {{path}}"
      }
     ]
    },
    {
     "title": "Disk IO Time Rate - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(diskio_read_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Read Time"
      },
      {
       "expr": "rate(diskio_write_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Write Time"
      },
      {
       "expr": "rate(diskio_io_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "IO Time"
      }
     ]
    },
    {
     "title": "Inodes Free - $disk_device",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "disk_inodes_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "disk_inodes_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Inodes - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "disk_inodes_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free on {{path}}"
      },
      {
       "expr": "disk_inodes_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used on {{path}}"
      }
     ]
    },
    {
     "title": "Disk IO Bytes Rate - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(diskio_read_bytes{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(diskio_write_bytes{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Write Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Device $disk_device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk used - $disk_device",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "disk_used_percent{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Disk capacity - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "disk_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free on {{path}}"
      },
      {
       "expr": "disk_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used on {{path}}"
      }
     ]
    },
    {
     "title": "Disk IO Time Rate - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(diskio_read_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Read Time"
      },
      {
       "expr": "rate(diskio_write_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Write Time"
      },
      {
       "expr": "rate(diskio_io_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "IO Time"
      }
     ]
    },
    {
     "title": "Inodes Free - $disk_device",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "disk_inodes_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "disk_inodes_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Inodes - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "disk_inodes_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free on {{path}}"
      },
      {
       "expr": "disk_inodes_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used on {{path}}"
      }
     ]
    },
    {
     "title": "Disk IO Bytes Rate - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(diskio_read_bytes{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(diskio_write_bytes{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Write Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Device $disk_device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk used - $disk_device",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "disk_used_percent{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Disk capacity - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "disk_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free on {{path}}"
      },
      {
       "expr": "disk_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used on {{path}}"
      }
     ]
    },
    {
     "title": "Disk IO Time Rate - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(diskio_read_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Read Time"
      },
      {
       "expr": "rate(diskio_write_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Write Time"
      },
      {
       "expr": "rate(diskio_io_time{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "IO Time"
      }
     ]
    },
    {
     "title": "Inodes Free - $disk_device",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "disk_inodes_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "disk_inodes_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Inodes - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "disk_inodes_free{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Free on {{path}}"
      },
      {
       "expr": "disk_inodes_used{instance=\"$node:$port\", device=\"$disk_device\", disk_device!=\"All\"}",
       "legendFormat": "Used on {{path}}"
      }
     ]
    },
    {
     "title": "Disk IO Bytes Rate - $disk_device",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(diskio_read_bytes{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(diskio_write_bytes{instance=\"$node:$port\", name=\"$disk_device\", disk_device!=\"All\"}[5m])",
       "legendFormat": "Write Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Device $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_bytes_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(net_packets_sent{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Sent {{interface}}"
      },
      {
       "expr": "rate(net_packets_recv{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "Received {{interface}}"
      }
     ]
    },
    {
     "title": "Errors In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Errors Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Error & Drop Rate - $interface",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(net_err_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_in"
      },
      {
       "expr": "rate(net_err_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "error_out"
      },
      {
       "expr": "rate(net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_in"
      },
      {
       "expr": "rate(net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}[5m])",
       "legendFormat": "drop_out"
      }
     ]
    },
    {
     "title": "Drop In Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_in{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Drop Out Total - $interface",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "net_drop_out{interface=\"$interface\", interface!=\"All\", instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  }
 ]
}