{
 "title": "Prometheus metrics",
 "description": "Metrics about Prometheus",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(prometheus_build_info, job)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(prometheus_build_info{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(prometheus_build_info{instance=~\"$host:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Samples Appended",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$host:$port\"}[5m]))",
     "legendFormat": "samples"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds{instance=~\"$host:.*\"}) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"$job\",instance=~\"$host:$port\"})",
     "legendFormat": "p8s process resident memory"
    },
    {
     "expr": "rate(process_virtual_memory_bytes{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "WAL Corruptions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_corruptions_total{job=~\"$job\",instance=~\"$host:$port\"}"
    }
   ]
  },
  {
   "title": "Active Appenders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_active_appenders{job=~\"$job\",instance=~\"$host:$port\"})",
     "legendFormat": "active_appenders"
    },
    {
     "expr": "sum(process_open_fds{job=~\"$job\",instance=~\"$host:$port\"})",
     "legendFormat": "open_fds"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=~\"$job\",instance=~\"$host:$port\"}",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Head Block GC Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds{instance=~\"$host:$port\",quantile=\"0.99\"}",
     "legendFormat": "duration-p99"
    },
    {
     "expr": "irate(prometheus_tsdb_head_gc_duration_seconds_count{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "collections"
    }
   ]
  },
  {
   "title": "Compaction Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_tsdb_compaction_duration_bucket{job=~\"$job\",instance=~\"$host:$port\"}[5m])) by (le))",
     "legendFormat": "duration-{{p99}}"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_total{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_failed_total{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_triggered_total{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "triggered"
    }
   ]
  },
  {
   "title": "Reload Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=~\"$job\",instance=~\"$host:$port\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "Rule Group Eval Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_rule_group_duration_seconds{job=~\"$job\",instance=~\"$host:$port\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Rule Group Eval Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "missed"
    },
    {
     "expr": "rate(prometheus_rule_group_iterations_total{job=~\"$job\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "iterations"
    }
   ]
  }
 ]
}